### ISSUE TITLE
./main.go:43:14: undefined: initializeApp

### ISSUE THREAD

**Issue by cn3c3p** [chenmingyong0423/fnote#34]
在调试server过程报错：./main.go:43:14: undefined: initializeApp

**Comment by chenmingyong0423** [comment]
如果你是通过终端的方式运行 `server` 项目，你不应该使用 `go run main.go`，因为在 `main.go` 文件里，引用了其他文件的代码，单纯的 `go run main.go` 命令只会编译 `main.go` 文件，其他文件是没有包含在内的，因此会找不到这个函数。

你可以通过使用 `go run .` 命令来运行项目，这会指示 Go 编译当前目录下的所有 `.go` 文件。
